<?php
$databasestuds = "
agonafer@studnet.eh-ludwigsburg.de
bader3@studnet.eh-ludwigsburg.de
bartesch@studnet.eh-ludwigsburg.de
barthel1@studnet.eh-ludwigsburg.de
bauer4@studnet.eh-ludwigsburg.de
baumgart2@studnet.eh-ludwigsburg.de
bayer1@studnet.eh-ludwigsburg.de
bayindir1@studnet.eh-ludwigsburg.de
beck3@studnet.eh-ludwigsburg.de
behringer1@studnet.eh-ludwigsburg.de
biesinger@studnet.eh-ludwigsburg.de
boemer@studnet.eh-ludwigsburg.de
braun7@studnet.eh-ludwigsburg.de
brenneisen1@studnet.eh-ludwigsburg.de
brieger@studnet.eh-ludwigsburg.de
buerkle@studnet.eh-ludwigsburg.de
burkhardt1@studnet.eh-ludwigsburg.de
celik@studnet.eh-ludwigsburg.de
clyne@studnet.eh-ludwigsburg.de
dallosteria@studnet.eh-ludwigsburg.de
doerne@studnet.eh-ludwigsburg.de
drechsel1@studnet.eh-ludwigsburg.de
durner1@studnet.eh-ludwigsburg.de
elster@studnet.eh-ludwigsburg.de
eppler1@studnet.eh-ludwigsburg.de
erdogan@studnet.eh-ludwigsburg.de
ezzedine@studnet.eh-ludwigsburg.de
fladerer@studnet.eh-ludwigsburg.de
franconieri@studnet.eh-ludwigsburg.de
friess@studnet.eh-ludwigsburg.de
fritton1@studnet.eh-ludwigsburg.de
fuchs3@studnet.eh-ludwigsburg.de
gmeineder1@studnet.eh-ludwigsburg.de
goezuebueyuek@studnet.eh-ludwigsburg.de
groetz@studnet.eh-ludwigsburg.de
grund@studnet.eh-ludwigsburg.de
haas3@studnet.eh-ludwigsburg.de
haeffner1@studnet.eh-ludwigsburg.de
hallauer@studnet.eh-ludwigsburg.de
halupczok@studnet.eh-ludwigsburg.de
hartenstein@studnet.eh-ludwigsburg.de
herrmann3@studnet.eh-ludwigsburg.de
hilbert@studnet.eh-ludwigsburg.de
hintzenstern@studnet.eh-ludwigsburg.de
hoche@studnet.eh-ludwigsburg.de
isiktas@studnet.eh-ludwigsburg.de
joiko@studnet.eh-ludwigsburg.de
kalman@studnet.eh-ludwigsburg.de
keller2@studnet.eh-ludwigsburg.de
kevin@studnet.eh-ludwigsburg.de
kirchner@studnet.eh-ludwigsburg.de
klett@studnet.eh-ludwigsburg.de
kniel1@studnet.eh-ludwigsburg.de
koch7@studnet.eh-ludwigsburg.de
koczy@studnet.eh-ludwigsburg.de
koehler2@studnet.eh-ludwigsburg.de
koerner@studnet.eh-ludwigsburg.de
koudoagbo1@studnet.eh-ludwigsburg.de
kuecuekkaya@studnet.eh-ludwigsburg.de
lang10@studnet.eh-ludwigsburg.de
langer@studnet.eh-ludwigsburg.de
laudien@studnet.eh-ludwigsburg.de
lehle@studnet.eh-ludwigsburg.de
leihenseder@studnet.eh-ludwigsburg.de
lindenberger@studnet.eh-ludwigsburg.de
maiwald2@studnet.eh-ludwigsburg.de
mayer4@studnet.eh-ludwigsburg.de
meissner3@studnet.eh-ludwigsburg.de
menihart@studnet.eh-ludwigsburg.de
merk@studnet.eh-ludwigsburg.de
middendorf@studnet.eh-ludwigsburg.de
miriam.janeczek@studnet.eh-ludwigsburg.de
moosmayer@studnet.eh-ludwigsburg.de
mueller19@studnet.eh-ludwigsburg.de
nataliia.chudovska@studnet.eh-ludwigsburg.de
oezek2@studnet.eh-ludwigsburg.de
osswald4@studnet.eh-ludwigsburg.de
ott@studnet.eh-ludwigsburg.de
pfaff@studnet.eh-ludwigsburg.de
pfeifer2@studnet.eh-ludwigsburg.de
pitakoudes1@studnet.eh-ludwigsburg.de
raach@studnet.eh-ludwigsburg.de
rau1@studnet.eh-ludwigsburg.de
rau2@studnet.eh-ludwigsburg.de
renner3@studnet.eh-ludwigsburg.de
rentschler4@studnet.eh-ludwigsburg.de
renz4@studnet.eh-ludwigsburg.de
riede1@studnet.eh-ludwigsburg.de
rose@studnet.eh-ludwigsburg.de
rothenbaecher@studnet.eh-ludwigsburg.de
rueckert@studnet.eh-ludwigsburg.de
schaetzler@studnet.eh-ludwigsburg.de
schmoll1@studnet.eh-ludwigsburg.de
schneider13@studnet.eh-ludwigsburg.de
schrade@studnet.eh-ludwigsburg.de
schreiber1@studnet.eh-ludwigsburg.de
schroeter2@studnet.eh-ludwigsburg.de
schuster7@studnet.eh-ludwigsburg.de
schwab2@studnet.eh-ludwigsburg.de
schwarz6@studnet.eh-ludwigsburg.de
schwoererboehning@studnet.eh-ludwigsburg.de
siber@studnet.eh-ludwigsburg.de
speidel@studnet.eh-ludwigsburg.de
spinner3@studnet.eh-ludwigsburg.de
stark@studnet.eh-ludwigsburg.de
steber@studnet.eh-ludwigsburg.de
stepper@studnet.eh-ludwigsburg.de
stuber@studnet.eh-ludwigsburg.de
thumulla@studnet.eh-ludwigsburg.de
tietze@studnet.eh-ludwigsburg.de
tressl@studnet.eh-ludwigsburg.de
vocino@studnet.eh-ludwigsburg.de
vonneubeck@studnet.eh-ludwigsburg.de
wagner5@studnet.eh-ludwigsburg.de
wahl2@studnet.eh-ludwigsburg.de
weigelt@studnet.eh-ludwigsburg.de
wenninger@studnet.eh-ludwigsburg.de
wilhelm1@studnet.eh-ludwigsburg.de
winterhalter1@studnet.eh-ludwigsburg.de
wohlbold@studnet.eh-ludwigsburg.de
wollmann1@studnet.eh-ludwigsburg.de
wondratsch@studnet.eh-ludwigsburg.de
zimmermann7@studnet.eh-ludwigsburg.de
";

$databaseempl = "
a.bartz@eh-ludwigsburg.de
a.dietzsch@eh-ludwigsburg.de
a.franke@eh-ludwigsburg.de
a.rabe@eh-ludwigsburg.de
a.steidl@eh-ludwigsburg.de
a.walter@eh-ludwigsburg.de
b.aschenbrenner-wellmann@eh-ludwigsburg.de
b.gerst@eh-ludwigsburg.de
b.goerder@eh-ludwigsburg.de
b.groner@eh-ludwigsburg.de
b.heinrich@eh-ludwigsburg.de
c.eylmann@eh-ludwigsburg.de
c.grimm@eh-ludwigsburg.de
c.schulz@eh-ludwigsburg.de
d.minke@eh-ludwigsburg.de
e.hammer@eh-ludwigsburg.de
e.nicolai@eh-ludwigsburg.de
e.reichmann@eh-ludwigsburg.de
e.schierer@eh-ludwigsburg.de
f.tirschmann@eh-ludwigsburg.de
f.woertz@eh-ludwigsburg.de
g.ulshoefer@eh-ludwigsburg.de
g.weiss@eh-ludwigsburg.de
h.fink@eh-ludwigsburg.de
h.stammer@eh-ludwigsburg.de
j.alber@eh-ludwigsburg.de
j.jerg@eh-ludwigsburg.de
j.mueller@eh-ludwigsburg.de
j.possinger@eh-ludwigsburg.de
j.zieger@eh-ludwigsburg.de
k.baur@eh-ludwigsburg.de
k.brukamp@eh-ludwigsburg.de
k.kraft@eh-ludwigsburg.de
k.sanders@eh-ludwigsburg.de
k.schloer@eh-ludwigsburg.de
l.ebert@eh-ludwigsburg.de
l.hein@eh-ludwigsburg.de
m.gese@eh-ludwigsburg.de
m.hees@eh-ludwigsburg.de
m.knab@eh-ludwigsburg.de
m.loeffler@eh-ludwigsburg.de
m.madew@eh-ludwigsburg.de
m.rehm@eh-ludwigsburg.de
m.rutkowski@eh-ludwigsburg.de
m.schnabel@eh-ludwigsburg.de
m.sieper@eh-ludwigsburg.de
n.collmar@eh-ludwigsburg.de
n.hartmann@eh-ludwigsburg.de
n.pfullinger@eh-ludwigsburg.de
n.sonnberger@eh-ludwigsburg.de
p.hoefflin@eh-ludwigsburg.de
p.schiffer@eh-ludwigsburg.de
r.ahlrichs@eh-ludwigsburg.de
r.horak@eh-ludwigsburg.de
r.mueller@eh-ludwigsburg.de
s.danz@eh-ludwigsburg.de
s.duck@eh-ludwigsburg.de
s.fietkau@eh-ludwigsburg.de
s.gatter@eh-ludwigsburg.de
s.goeke@eh-ludwigsburg.de
s.hoffmann@eh-ludwigsburg.de
s.kaiser@eh-ludwigsburg.de
s.kretzschmar@eh-ludwigsburg.de
s.relle@eh-ludwigsburg.de
s.ries@eh-ludwigsburg.de
s.thalheim@eh-ludwigsburg.de
s.weber@eh-ludwigsburg.de
t.bek@eh-ludwigsburg.de
t.bloch@eh-ludwigsburg.de
t.dietzsch@eh-ludwigsburg.de
t.hoernig@eh-ludwigsburg.de
u.karl@eh-ludwigsburg.de
u.leopold@eh-ludwigsburg.de
v.buddenberg@eh-ludwigsburg.de
v.segrt@eh-ludwigsburg.de
v.sing@eh-ludwigsburg.de
w.ilg@eh-ludwigsburg.de
";

$databasemails = $databasestuds . $databaseempl;
?>