<?php

//ini_set('display_errors', 1);
//ini_set('display_startup_errors', 1);
//error_reporting(E_ALL);
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/



function translate($source_text, $target_lang) {
	$target_lang = strtoupper($target_lang);
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, 'https://api-free.deepl.com/v2/translate');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, "auth_key=dd0082e1-f69c-191e-9ec7-a2508da03b8a:fx&text=".$source_text."&target_lang=".$target_lang);

	$headers = array();
	$headers[] = 'Content-Type: application/x-www-form-urlencoded';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch);
	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);

	$translatedWords = json_decode($result, true); // Decode the word
	$result = $translatedWords['translations'][0]['text']; // Search the word

	return $result; // Display the word
}

// usage
// echo translate("How are you today?", "DE");